### ISSUE TITLE
Update it to today's version of jekyll-assets

### ISSUE THREAD

**Issue by iBobik** [ixti/jekyll-assets-demo#2]
It will also require to remove ERB

**Comment by ixti** [comment]
This is just a auxiliary repo for the post I wrote pretty [long ago](http://ixti.net/software/2012/12/30/unleash-mr-hyde-introduction-of-jekyll-assets.html) when I released `jekyll-assets` and received *docs can be better* request. :))

In the middle of 2015 I have stepped out from `jekyll-assets` development and `2.0.0+` was heavily rewritten by @envygeeks.

So if you want you can provide a PR with example blog to `jekyll-assets` current upstream. But this particular repo is just blog post files with history ;))
